version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  backend:
    depends_on:
      - db
    image: javatest:0.0.3
    container_name: backend
    env_file: .env
    ports:
      - 8080:8080