name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "Hello World!"
      - run: echo $MY_SECRET
      - name: Run script file
        run: |
         chmod +x ./run.sh
        shell: bash
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         port: 22
         script: echo "Hello World"
      - name: copy file to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
         local: ./run.sh
         remote: /home/lekhana/run.sh
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }} 